name: tumor
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - matplotlib
  - streamlit
  - opencv
  - pip:
      - pillow
      - setuptools
      - sympy
      - torch==2.8.0
      - torchvision==0.23.0
